spring:
  profiles:
    active: "dev"
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  #      ddl-auto: create-drop
  #      ddl-auto: validate

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SYSTEM
    password: password
    driver-class-name: oracle.jdbc.OracleDriver